name: C CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Accessible
        run: chmod +x run.sh
      - name: Build and Test
        run: ./run.sh
